version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Dependencies
          command: apt-get -yq install g++ make

      - run:
          name: Build
          command: make
